/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pidev.tunipharma.gui;

import java.awt.Graphics;
import javax.swing.JScrollBar;
import javax.swing.JScrollPane;
import javax.swing.JViewport;
import pidev.tunipharma.classes.Compte;
import pidev.tunipharma.utils.GUIUtils;
import pidev.tunipharma.utils.Session;

/**
 *
 * @author elron
 */
public class TuniPharmaMain extends javax.swing.JFrame {

    /**
     * Creates new form TuniPharmaMain
     */
    public TuniPharmaMain() {
        initComponents();

        // Verification si utilisateur connecté
        Compte cpt = Session.getCptConn();
        if (Session.getSes() == null) {
            lbNomUser.setText("DÉCONNECTÉ");
            lbInfoUser.setText("");
            panelIconUtilisateur.add(Compte.getImageCpt(-1));
        } else {
            lbNomUser.setText("Bonjour " + cpt.getPrenom_cpt() + " " + cpt.getNom_cpt());
            lbInfoUser.setText("Type Compte : " + cpt.getTypeCptNom());
            panelIconUtilisateur = Compte.getImageCpt(cpt.getType_cpt());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        panelCorps = new javax.swing.JPanel();
        panelInfoUtilisateur = new javax.swing.JPanel();
        lbNomUser = new javax.swing.JLabel();
        panelIconUtilisateur = new javax.swing.JPanel();
        lbInfoUser = new javax.swing.JLabel();
        menuBarMain = new javax.swing.JMenuBar();
        menuFichier = new javax.swing.JMenu();
        menuItemQuiter = new javax.swing.JMenuItem();
        menuPharmacie = new javax.swing.JMenu();
        menuItemRechPha = new javax.swing.JMenuItem();
        menuMonCpt = new javax.swing.JMenu();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        menuItemGestPha = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        menuItemStats = new javax.swing.JMenuItem();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelCorps.setLayout(null);
        panelCorps.setOpaque(false);

        javax.swing.GroupLayout panelCorpsLayout = new javax.swing.GroupLayout(panelCorps);
        panelCorps.setLayout(panelCorpsLayout);
        panelCorpsLayout.setHorizontalGroup(
            panelCorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1080, Short.MAX_VALUE)
        );
        panelCorpsLayout.setVerticalGroup(
            panelCorpsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 862, Short.MAX_VALUE)
        );

        panelInfoUtilisateur.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        panelInfoUtilisateur.setOpaque(false);

        panelIconUtilisateur.setBorder(javax.swing.BorderFactory.createCompoundBorder());

        javax.swing.GroupLayout panelIconUtilisateurLayout = new javax.swing.GroupLayout(panelIconUtilisateur);
        panelIconUtilisateur.setLayout(panelIconUtilisateurLayout);
        panelIconUtilisateurLayout.setHorizontalGroup(
            panelIconUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 70, Short.MAX_VALUE)
        );
        panelIconUtilisateurLayout.setVerticalGroup(
            panelIconUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout panelInfoUtilisateurLayout = new javax.swing.GroupLayout(panelInfoUtilisateur);
        panelInfoUtilisateur.setLayout(panelInfoUtilisateurLayout);
        panelInfoUtilisateurLayout.setHorizontalGroup(
            panelInfoUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInfoUtilisateurLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelInfoUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbNomUser, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(lbInfoUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelIconUtilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelInfoUtilisateurLayout.setVerticalGroup(
            panelInfoUtilisateurLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelIconUtilisateur, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelInfoUtilisateurLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lbNomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbInfoUser, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
        );

        menuFichier.setText("Fichier");

        menuItemQuiter.setText("Quitter");
        menuItemQuiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemQuiterActionPerformed(evt);
            }
        });
        menuFichier.add(menuItemQuiter);

        menuBarMain.add(menuFichier);

        menuPharmacie.setText("Pharmacies");

        menuItemRechPha.setText("Recherche pharmacie");
        menuItemRechPha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuItemRechPhaActionPerformed(evt);
            }
        });
        menuPharmacie.add(menuItemRechPha);

        menuBarMain.add(menuPharmacie);

        menuMonCpt.setText("Mon Compte");

        jMenuItem5.setText("Informations personnelles");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        menuMonCpt.add(jMenuItem5);

        jMenuItem6.setText("Mes messages");
        menuMonCpt.add(jMenuItem6);

        menuBarMain.add(menuMonCpt);

        jMenu1.setText("Administrateur");

        menuItemGestPha.setText("Gestion des comptes");
        jMenu1.add(menuItemGestPha);

        jMenuItem2.setText("Gestion des pharmacies");
        jMenu1.add(jMenuItem2);

        menuItemStats.setText("Statistique");
        jMenu1.add(menuItemStats);

        menuBarMain.add(jMenu1);

        setJMenuBar(menuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelCorps, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelInfoUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(panelInfoUtilisateur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCorps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        panelCorps.removeAll();
        GUIUtils.addCompPanel(panelCorps, new InterfaceUtilisateur().getComponents());
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void menuItemQuiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemQuiterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuItemQuiterActionPerformed

    private void menuItemRechPhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuItemRechPhaActionPerformed
        // TODO add your handling code here:
        panelCorps.removeAll();
        GUIUtils.addCompPanel(panelCorps, new InterfaceRecherchePharmacie().getComponents());
    }//GEN-LAST:event_menuItemRechPhaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TuniPharmaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TuniPharmaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TuniPharmaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TuniPharmaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TuniPharmaMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JLabel lbInfoUser;
    private javax.swing.JLabel lbNomUser;
    private javax.swing.JMenuBar menuBarMain;
    private javax.swing.JMenu menuFichier;
    private javax.swing.JMenuItem menuItemGestPha;
    private javax.swing.JMenuItem menuItemQuiter;
    private javax.swing.JMenuItem menuItemRechPha;
    private javax.swing.JMenuItem menuItemStats;
    private javax.swing.JMenu menuMonCpt;
    private javax.swing.JMenu menuPharmacie;
    private javax.swing.JPanel panelCorps;
    private javax.swing.JPanel panelIconUtilisateur;
    private javax.swing.JPanel panelInfoUtilisateur;
    // End of variables declaration//GEN-END:variables
}
